version: "3.3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.33
    restart: always
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    env_file: 
      - "./root.env"
    networks:
      - app-network
  # Backend
  backend:
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - "./root.env"
    container_name: backend
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    expose:
      - 4000
      - 4001
    links:
      - mysql
    volumes:
      - "./server/:/usr/src/app"
      - "/usr/src/app/node_modules"
      - assets:/usr/src/app/uploads
    env_file: #tell the backend to use the .env file in the root directory
      - "./.env"
    environment:
      NODE_ENV: "production"
    networks:
      - app-network
  # Frontend
  frontend:
    stdin_open: true
    tty: true
    restart: always
    container_name: frontend
    build:
      context: ./client/
      dockerfile: Dockerfile.prod
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
      - assets:/app/public/data
    ports:
      - 80:80
      - 443:443
    links:
      - backend
    env_file:
      - "client/react.env"
    networks:
      - app-network
# Volumes
volumes:
  my-db: #docker stores our db for us so our data is persistent
  assets:
# Network
networks:
  app-network:
    driver: bridge
