version: "3.3"

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  mysql:
    container_name: mysql
    image: mysql:5.7.33
    restart: always
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    env_file: 
      - "./.env"

  backend:
    stdin_open: true
    tty: true
    container_name: backend
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 4001:4001
    expose:
      - 4000
      - 4001
    links:
      - mysql
    volumes:
      - "./server/:/usr/src/app"
    env_file: #tell the backend to use the .env file in the root directory
      - "./.env"

  frontend:
    stdin_open: true
    tty: true
    container_name: frontend
    restart: always
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    links:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ".env"
volumes:
  my-db: #docker stores our db for us so our data is persistent
