version: "3.3"

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  mysql:
    container_name: mysql
    image: mysql:5.6.51
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  backend:
    stdin_open: true
    tty: true
    container_name: backend
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    links:
      - mysql
    volumes:
      - "./server/:/usr/src/app"

  frontend:
    stdin_open: true
    tty: true
    container_name: frontend
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    links:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  my-db: #docker stores our db for us so our data is persistent
