# pull official base image
FROM node:15.7.0-alpine3.12

# set working directory
WORKDIR /usr/src/app

# Install build essentials
RUN apk add --update alpine-sdk

COPY ./ ./
RUN npm install

CMD [ "node","index.js" ]
